name = "NodesAndModes"
uuid = "7aca2e03-f7e2-4192-9ec8-f4ca66d597fb"
authors = ["Jesse Chan", "Yimin Lin"]
version = "1.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DelimitedFiles = "1"
LinearAlgebra = "<0.0.1, 1" 
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
