[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
NodesAndModes = "7aca2e03-f7e2-4192-9ec8-f4ca66d597fb"

[compat]
Documenter = "0.25, 0.26, 0.27"
DocumenterTools = "0.1"
NodesAndModes = "0.9, 1"
